[input]
html_selector = "main"
base_directory = "/home/runner/work/pelican_website_raw/pelican_website_raw/output"

[[input.files]]
path = "pages/about.html"
url = "/pages/about.html"
title = "About"

[[input.files]]
path = "pages/about2.html"
url = "/pages/about.html"
title = "About"

[[input.files]]
path = "pages/link.html"
url = "/pages/link.html"
title = "Link"

[[input.files]]
path = "blogs/softwares/pku_to_xmol.html"
url = "/blogs/softwares/pku_to_xmol.html"
title = "PKU To Xmol Chrome Plugin"

[[input.files]]
path = "blogs/publications/chemsci-d3sc03722c.html"
url = "/blogs/publications/chemsci-d3sc03722c.html"
title = "Divergent total syntheses of ITHQ-type bis-β-carboline alkaloids by regio-selective formal aza-[4 + 2] cycloaddition and late-stage C–H functionalization"
